use async_trait::async_trait;
use thiserror::Error;

/// Error types encountered during embedding operations.
#[derive(Debug, Error)]
pub enum EmbeddingError {
    /// Provider is unreachable or unavailable.
    #[error("Provider unavailable: {0}")]
    Unavailable(String),
    /// Computation failed during embedding generation.
    #[error("Embedding failed: {0}")]
    ComputationFailed(String),
    /// Input token count exceeds the provider's max supported limit.
    #[error("Input too long: {len} tokens, max {max}")]
    InputTooLong {
        /// Number of tokens in input.
        len: usize,
        /// Maximum tokens allowed.
        max: usize,
    },
}

/// Abstraction for all embedding providers (OllamaEmbedder, OnnxEmbedder, MockEmbedder).
#[async_trait]
pub trait EmbeddingProvider: Send + Sync + 'static {
    /// Returns the provider identifier/name (e.g. for logging/debugging).
    fn provider_name(&self) -> &str;

    /// Generates an embedding vector for the given text.
    async fn embed(&self, text: &str) -> Result<Vec<f32>, EmbeddingError>;

    /// Returns the dimensionality of embeddings generated by this provider.
    fn embedding_dim(&self) -> usize;

    /// Generates embeddings for multiple texts.
    async fn embed_batch(&self, texts: &[&str]) -> Result<Vec<Vec<f32>>, EmbeddingError> {
        let mut results = Vec::with_capacity(texts.len());
        for text in texts {
            results.push(self.embed(text).await?);
        }
        Ok(results)
    }
}

/// Abstraction for text generation / LLM engines.
#[async_trait]
pub trait TextGenerator: Send + Sync + 'static {
    /// Generates text response for a given prompt.
    async fn generate_text(&self, prompt: &str) -> crate::Result<String>;
}

/// Blanket implementation of `TextEmbeddingEngine` for any `EmbeddingProvider`.
#[async_trait]
impl<T: EmbeddingProvider> super::TextEmbeddingEngine for T {
    async fn embed(&self, text: &str) -> crate::Result<Vec<f32>> {
        T::embed(self, text)
            .await
            .map_err(|e| crate::MemFuseError::Internal(e.to_string()))
    }

    async fn embed_batch(&self, texts: &[&str]) -> crate::Result<Vec<Vec<f32>>> {
        T::embed_batch(self, texts)
            .await
            .map_err(|e| crate::MemFuseError::Internal(e.to_string()))
    }
}

/// Deterministic mock embedding provider for tests.
pub struct MockEmbedder {
    /// Target embedding dimensionality.
    pub dim: usize,
    /// Fixed output vector for deterministic testing.
    pub fixed_output: Option<Vec<f32>>,
}

impl MockEmbedder {
    /// Creates a new `MockEmbedder` with the specified dimension.
    pub fn new(dim: usize) -> Self {
        Self {
            dim,
            fixed_output: None,
        }
    }

    /// Creates a new `MockEmbedder` with a fixed output vector.
    pub fn with_fixed_output(fixed_output: Vec<f32>) -> Self {
        let dim = fixed_output.len();
        Self {
            dim,
            fixed_output: Some(fixed_output),
        }
    }
}

#[async_trait]
impl EmbeddingProvider for MockEmbedder {
    fn provider_name(&self) -> &str {
        "mock"
    }

    async fn embed(&self, _text: &str) -> Result<Vec<f32>, EmbeddingError> {
        Ok(self
            .fixed_output
            .clone()
            .unwrap_or_else(|| vec![0.0f32; self.dim]))
    }

    fn embedding_dim(&self) -> usize {
        self.dim
    }
}
