use super::BoxFuture;
use thiserror::Error;

/// Error types encountered during embedding operations.
#[derive(Debug, Error)]
pub enum EmbeddingError {
    /// Provider is unreachable or unavailable.
    #[error("Provider unavailable: {0}")]
    Unavailable(String),
    /// Computation failed during embedding generation.
    #[error("Embedding failed: {0}")]
    ComputationFailed(String),
    /// Input token count exceeds the provider's max supported limit.
    #[error("Input too long: {len} tokens, max {max}")]
    InputTooLong {
        /// Number of tokens in input.
        len: usize,
        /// Maximum tokens allowed.
        max: usize,
    },
}

/// Abstraction for all embedding providers (OllamaEmbedder, OnnxEmbedder, MockEmbedder).
pub trait EmbeddingProvider: Send + Sync + 'static {
    /// Returns the provider identifier/name (e.g. for logging/debugging).
    fn provider_name(&self) -> &str;

    /// Generates an embedding vector for the given text.
    fn embed<'a>(&'a self, text: &'a str) -> BoxFuture<'a, Result<Vec<f32>, EmbeddingError>>;

    /// Returns the dimensionality of embeddings generated by this provider.
    fn embedding_dim(&self) -> usize;

    /// Generates embeddings for multiple texts.
    fn embed_batch<'a>(
        &'a self,
        texts: &'a [&'a str],
    ) -> BoxFuture<'a, Result<Vec<Vec<f32>>, EmbeddingError>> {
        Box::pin(async move {
            let mut results = Vec::with_capacity(texts.len());
            for text in texts {
                results.push(self.embed(text).await?);
            }
            Ok(results)
        })
    }
}

/// Abstraction for text generation / LLM engines.
pub trait TextGenerator: Send + Sync + 'static {
    /// Generates text response for a given prompt.
    fn generate_text<'a>(&'a self, prompt: &'a str) -> BoxFuture<'a, crate::Result<String>>;
}

/// Blanket implementation of `TextEmbeddingEngine` for any `EmbeddingProvider`.
impl<T: EmbeddingProvider> super::TextEmbeddingEngine for T {
    fn embed<'a>(&'a self, text: &'a str) -> BoxFuture<'a, crate::Result<Vec<f32>>> {
        Box::pin(async move {
            T::embed(self, text)
                .await
                .map_err(|e| crate::MemFuseError::Internal(e.to_string()))
        })
    }

    fn embed_batch<'a>(
        &'a self,
        texts: &'a [&'a str],
    ) -> BoxFuture<'a, crate::Result<Vec<Vec<f32>>>> {
        Box::pin(async move {
            T::embed_batch(self, texts)
                .await
                .map_err(|e| crate::MemFuseError::Internal(e.to_string()))
        })
    }
}

/// Deterministic mock embedding provider for tests.
pub struct MockEmbedder {
    /// Target embedding dimensionality.
    pub dim: usize,
    /// Fixed output vector for deterministic testing.
    pub fixed_output: Option<Vec<f32>>,
}

impl MockEmbedder {
    /// Creates a new `MockEmbedder` with the specified dimension.
    pub fn new(dim: usize) -> Self {
        Self {
            dim,
            fixed_output: None,
        }
    }

    /// Creates a new `MockEmbedder` with a fixed output vector.
    pub fn with_fixed_output(fixed_output: Vec<f32>) -> Self {
        let dim = fixed_output.len();
        Self {
            dim,
            fixed_output: Some(fixed_output),
        }
    }
}

impl EmbeddingProvider for MockEmbedder {
    fn provider_name(&self) -> &str {
        "mock"
    }

    async fn embed(&self, _text: &str) -> Result<Vec<f32>, EmbeddingError> {
        Ok(self
            .fixed_output
            .clone()
            .unwrap_or_else(|| vec![0.1f32; self.dim]))
    }

    fn embedding_dim(&self) -> usize {
        self.dim
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::traits::TextEmbeddingEngine;

    #[tokio::test]
    async fn test_embedding_error_display() {
        let err1 = EmbeddingError::Unavailable("server down".into());
        assert_eq!(err1.to_string(), "Provider unavailable: server down");

        let err2 = EmbeddingError::ComputationFailed("OOM".into());
        assert_eq!(err2.to_string(), "Embedding failed: OOM");

        let err3 = EmbeddingError::InputTooLong { len: 100, max: 50 };
        assert_eq!(err3.to_string(), "Input too long: 100 tokens, max 50");
    }

    #[tokio::test]
    async fn test_mock_embedder_methods() -> Result<(), Box<dyn std::error::Error>> {
        let embedder = MockEmbedder::new(4);
        assert_eq!(embedder.provider_name(), "mock");
        assert_eq!(embedder.embedding_dim(), 4);

        let vec = EmbeddingProvider::embed(&embedder, "test").await?;
        assert_eq!(vec, vec![0.1, 0.1, 0.1, 0.1]);

        let fixed = vec![1.0, 2.0, 3.0];
        let fixed_embedder = MockEmbedder::with_fixed_output(fixed.clone());
        assert_eq!(fixed_embedder.embedding_dim(), 3);
        let res = EmbeddingProvider::embed(&fixed_embedder, "hello").await?;
        assert_eq!(res, fixed);
        Ok(())
    }

    #[tokio::test]
    async fn test_embedding_provider_batch_and_blanket_trait(
    ) -> Result<(), Box<dyn std::error::Error>> {
        let embedder = MockEmbedder::new(2);
        let batch_res = EmbeddingProvider::embed_batch(&embedder, &["a", "b"]).await?;
        assert_eq!(batch_res.len(), 2);
        assert_eq!(batch_res[0], vec![0.1, 0.1]);

        // Test blanket impl of TextEmbeddingEngine for MockEmbedder
        let engine: &dyn TextEmbeddingEngine = &embedder;
        let single = engine.embed("text").await?;
        assert_eq!(single, vec![0.1, 0.1]);

        let batch = engine.embed_batch(&["x", "y"]).await?;
        assert_eq!(batch.len(), 2);
        Ok(())
    }
}
