import numpy as np
from typing import List, Optional, Dict, Any, Union, Tuple

class VectorIndexStats:
    num_vectors: int
    memory_usage_bytes: int
    num_layers: int

class StorageStats:
    num_segments: int
    total_size_bytes: int
    memtable_size_bytes: int

class DbStats:
    index_stats: VectorIndexStats
    storage_stats: StorageStats

class PySearchResult:
    id: str
    score: float
    metadata: Optional[Dict[str, Any]]

class PyDocument:
    id: str
    metadata: Optional[Dict[str, Any]]

class Collection:
    def insert(self, id: str, vector: np.ndarray, metadata: Optional[Dict[str, Any]] = None) -> None: ...
    def get(self, id: str) -> Optional[PyDocument]: ...
    def update(self, id: str, vector: np.ndarray, metadata: Optional[Dict[str, Any]] = None) -> None: ...
    def upsert(self, id: str, vector: np.ndarray, metadata: Optional[Dict[str, Any]] = None) -> None: ...
    def delete(self, id: str) -> None: ...
    def search(self, vector: np.ndarray, k: int, filter: Optional[Dict[str, Any]] = None) -> List[PySearchResult]: ...
    def hybrid_search(self, text: str, vector: np.ndarray, k: int) -> List[PySearchResult]: ...
    def repair(self) -> None: ...
    def relate(self, from_id: str, to_id: str, label: str) -> None: ...
    def scan_prefix(self, prefix: str = "") -> List[Tuple[str, Any]]: ...
    def scan(self, start: Optional[str] = None, end: Optional[str] = None) -> List[Tuple[str, Any]]: ...
    def insert_many(self, docs: List[Tuple[str, np.ndarray, Optional[Dict[str, Any]]]]) -> None: ...
    def upsert_many(self, docs: List[Tuple[str, np.ndarray, Optional[Dict[str, Any]]]]) -> None: ...
    def stats(self) -> VectorIndexStats: ...
    def __len__(self) -> int: ...
    def is_empty(self) -> bool: ...

class Db:
    def collection(self, name: str) -> Collection: ...
    def list_collections(self) -> List[str]: ...
    def drop_collection(self, name: str) -> None: ...
    def repair(self) -> None: ...
    def flush(self) -> None: ...
    def stats(self) -> DbStats: ...
    def __len__(self) -> int: ...
    def is_empty(self) -> bool: ...
    def __enter__(self) -> "Db": ...
    def __exit__(self, exc_type, exc_val, exc_tb) -> bool: ...
    
    # Facade methods for 'default' collection
    def insert(self, id: str, vector: np.ndarray, metadata: Optional[Dict[str, Any]] = None) -> None: ...
    def get(self, id: str) -> Optional[PyDocument]: ...
    def update(self, id: str, vector: np.ndarray, metadata: Optional[Dict[str, Any]] = None) -> None: ...
    def upsert(self, id: str, vector: np.ndarray, metadata: Optional[Dict[str, Any]] = None) -> None: ...
    def delete(self, id: str) -> None: ...
    def search(self, vector: np.ndarray, k: int, filter: Optional[Dict[str, Any]] = None) -> List[PySearchResult]: ...
    def hybrid_search(self, text: str, vector: np.ndarray, k: int) -> List[PySearchResult]: ...
    def relate(self, from_id: str, to_id: str, label: str) -> None: ...
    def scan_prefix(self, prefix: str = "") -> List[Tuple[str, Any]]: ...
    def scan(self, start: Optional[str] = None, end: Optional[str] = None) -> List[Tuple[str, Any]]: ...
    def insert_many(self, docs: List[Tuple[str, np.ndarray, Optional[Dict[str, Any]]]]) -> None: ...
    def upsert_many(self, docs: List[Tuple[str, np.ndarray, Optional[Dict[str, Any]]]]) -> None: ...

def open(
    path: str, 
    dimension: int = 1536, 
    max_elements: Optional[int] = None, 
    encryption_passphrase: Optional[str] = None, 
    distance_metric: Optional[str] = None
) -> Db: ...
