[package]
name = "memfuse-calibration"
version.workspace = true
edition.workspace = true

[dependencies]
memfuse-core = { path = "../memfuse-core" }
serde = { workspace = true, features = ["derive"] }
parking_lot = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
serde_json = { workspace = true }
